version: '3'

services:
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:stable
    restart: on-failure
    ports:
      - '80:80'
    volumes:
      - './${APP_NAME}:/var/www/html:ro,delegated'
      - './.docker/nginx:/var/log/nginx'
      - ./provisioning/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./provisioning/docker/nginx/conf.d:/etc/nginx/conf.d

    links:
      - php
      - db
    networks:
      - docker

  db:
    container_name: ${APP_NAME}-mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - docker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    environment:
      - PMA_HOST=${APP_NAME}-mariadb
      - PMA_PORT=3306
    restart: always
    ports:
      - 8081:80
    links:
      - db
    networks:
      - docker

  php:
    container_name: ${APP_NAME}-php
    image: php:7.4-fpm
    restart: on-failure
    volumes:
      - './${APP_NAME}:/var/www/html'
      - './.docker/php:/var/log/php'
    networks:
      - docker

  composer:
    image: composer:latest
    container_name: ${APP_NAME}-composer
    volumes:
      - ./${APP_NAME}:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - docker

networks:
  docker:
    driver: bridge
